# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_current_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='report_duration',
            field=models.IntegerField(choices=[(1, b'Daily'), (7, b'Weekly'), (30, b'Monthly')], default=30),
        ),
    ]
