# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_report_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='notify',
            field=models.BooleanField(default=True),
        ),
    ]
