# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_member_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='prioritize_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
