# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170308_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='notify',
        ),
    ]
