# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 16:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_member_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='priority_delay',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
    ]
