# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-14 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_check_nag_interval'),
        ('accounts', '0011_profile_priority_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='allowed_checks',
            field=models.ManyToManyField(to='api.Check'),
        ),
    ]
