# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-18 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_member_allowed_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='next_priority_notification',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
