# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-18 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170318_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='next_priority_notification',
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_priority',
            field=models.IntegerField(default=0),
        ),
    ]
