# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-18 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_check_nag_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='next_priority_notification',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
