# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_check_next_priority_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='nag_interval',
            new_name='nag',
        ),
    ]
