# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20170313_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='check_priority',
            field=models.IntegerField(choices=[(0, b'HIGH'), (1, b'MEDIUM'), (2, b'LOW')], default=1),
        ),
    ]
