# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20170313_1032'),
        ('api', '0028_check_next_priority_notification'),
    ]

    operations = [
    ]
