# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20170314_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='telegram_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='channel',
            name='kind',
            field=models.CharField(choices=[(b'email', b'Email'), (b'webhook', b'Webhook'), (b'sms', b'SMS'), (b'hipchat', b'HipChat'), (b'slack', b'Slack'), (b'pd', b'PagerDuty'), (b'po', b'Pushover'), (b'victorops', b'VictorOps')], max_length=20),
        ),
    ]
