# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20170320_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='telegram_chat_id',
            field=models.IntegerField(default=0),
        ),
    ]
